### PR TITLE
Moved output from info to debug

### PR DESCRIPTION
**Pull request by LazeMSS**

### CODE REVIEW

**Comment by foosel** [comment]
Having this log to info is intentional to signal that the replacement is taking place during normal operation in production environments.

Why do you want to make this less transparent?

**Comment by LazeMSS** [comment]
To stop flooding of the log file basically.

**Comment by foosel** [comment]
Hm... I see that this whole `wait` situation can probably spam a lot. How about this: Switch it to `debug`, but on the first replacement done on a connection, log that the replacements are being done because the firmware sends garbage. That way it still will land in the log (might be crucial for support, to check whether the plugin actually reacts or not without access to the user's terminal), but only once.

**Review by foosel — CHANGES_REQUESTED** [review]
Happy to merge if modified to make sure at least 1 line indicating plugin activity lands in the log.

**Comment by LazeMSS** [comment]
@foosel added a first run check :)

**Comment by foosel** [comment]
That really should be a member variable, not a global class constant. Usually plugins are only instantiated once, but this is still really bad practice as the first run is instance state, and definitely not a constant either.

**Comment by LazeMSS** [comment]
Will look asap

**Comment by LazeMSS** [comment]
Assign to me please :)

**Comment by foosel** [comment]
Already done ;) Can you take a look at the suggestion I just pushed?

**Review by LazeMSS — COMMENTED** [review]
Looks fine - i can't approve :)

**Review by foosel — APPROVED** [review]

**Comment by foosel** [comment]
I know, it was more a request for a sanity check ;)

**Comment by foosel** [comment]
I'll take care of a release next week. Also need to take care of some formatting and such, need to give it a final test, and that doesn't fit my schedule today :)

**Pull request merged**
